#!/usr/bin/env python3
"""
case_004 NREL Phase VI MRF · M-V64A-MESH-CONV-STUDY · Richardson trend analysis.

Reads force/moment time-series from h, h/2, h/4 cases and computes Cp/Ct
at each level + Richardson extrapolation. Tests monotonic convergence trend.

Reuses the parse logic from case/analyze_convergence.py (B56) for byte
fidelity with the canonical baseline computation.
"""
import re, statistics
from pathlib import Path

SANDBOX = Path("/Users/Zhuanz/Desktop/case_004_nrel_phase_vi_mrf")

NREL_BASELINE = {
    "U_inf": 7.0, "rho": 1.225, "A_ref": 79.43, "R": 5.029,
    "omega_rad_s": 7.539822369,
    "P_kW": 5.93, "T_N": 1240.0, "Cp": 0.40, "Ct": 0.52,
}


def read_force_dat(path):
    if not Path(path).exists():
        return []
    rows = []
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = re.split(r"\s+", line)
        try:
            t = float(parts[0])
            fx = float(parts[1].lstrip("("))
            fy = float(parts[2])
            fz = float(parts[3].rstrip(")"))
            rows.append((t, fx, fy, fz))
        except (ValueError, IndexError):
            continue
    return rows


def window_stats(rows, last_n=20):
    if len(rows) < 2:
        return None
    tail = rows[-last_n:] if len(rows) >= last_n else rows
    mx = statistics.fmean(r[1] for r in tail)
    sx = statistics.pstdev(r[1] for r in tail) if len(tail) > 1 else 0.0
    return {
        "n": len(tail),
        "t0": tail[0][0], "t1": tail[-1][0],
        "mean_x": mx, "stdev_x": sx,
        "min_x": min(r[1] for r in tail),
        "max_x": max(r[1] for r in tail),
        "osc_frac": (max(r[1] for r in tail) - min(r[1] for r in tail)) / max(abs(mx), 1e-12),
    }


def compute_cp_ct(level_name, case_dir):
    rotor_force  = read_force_dat(case_dir / "postProcessing/forces_rotor/0/force.dat")
    rotor_moment = read_force_dat(case_dir / "postProcessing/forces_rotor/0/moment.dat")
    blades_force = read_force_dat(case_dir / "postProcessing/forces_thrust_blades/0/force.dat")

    if not rotor_moment or not blades_force:
        return {"level": level_name, "missing": True,
                "rotor_moment_rows": len(rotor_moment),
                "blades_force_rows": len(blades_force)}

    fr = window_stats(rotor_force, last_n=20)
    mr = window_stats(rotor_moment, last_n=20)
    fb = window_stats(blades_force, last_n=20)

    # Cp = |M_x|·omega / (0.5·rho·A·U^3)
    Mx_mean = mr["mean_x"]
    Tx_mean = fb["mean_x"]  # blade-only thrust
    U = NREL_BASELINE["U_inf"]
    rho = NREL_BASELINE["rho"]
    A = NREL_BASELINE["A_ref"]
    omega = NREL_BASELINE["omega_rad_s"]

    P_W = abs(Mx_mean) * omega
    Cp = P_W / (0.5 * rho * A * U**3)
    Ct = abs(Tx_mean) / (0.5 * rho * A * U**2)

    return {
        "level": level_name,
        "missing": False,
        "last_t": rotor_moment[-1][0],
        "n_rows": len(rotor_moment),
        "Mx_mean": Mx_mean, "Mx_stdev": mr["stdev_x"], "Mx_osc_frac": mr["osc_frac"],
        "Fx_rotor_mean": fr["mean_x"], "Fx_rotor_stdev": fr["stdev_x"], "Fx_rotor_osc_frac": fr["osc_frac"],
        "Fx_blades_mean": Tx_mean, "Fx_blades_stdev": fb["stdev_x"], "Fx_blades_osc_frac": fb["osc_frac"],
        "P_kW": P_W / 1000.0,
        "Cp": Cp,
        "Ct": Ct,
    }


def main():
    print("=" * 72)
    print("case_004 mesh convergence study · M-V64A-MESH-CONV-STUDY")
    print("=" * 72)

    # Canonical h: B56 baseline (hardcoded from convergence_analysis.txt
    # generated by case/analyze_convergence.py · 2026-05-15 04:30). Do NOT
    # re-read case/postProcessing because case/ is owned by B57 (out of scope).
    h_baseline = {
        "level": "h (B56 canonical, 919,762 cells)",
        "missing": False,
        "last_t": 500.0, "n_rows": 50,
        "Mx_mean": -10188.67, "Mx_stdev": 258.90, "Mx_osc_frac": 0.0820,
        "Fx_rotor_mean": -398.47, "Fx_rotor_stdev": 37.78, "Fx_rotor_osc_frac": 0.3451,
        "Fx_blades_mean": -400.86, "Fx_blades_stdev": 38.07, "Fx_blades_osc_frac": None,
        "P_kW": 76.821,
        "Cp": 4.6036,
        "Ct": 0.1682,
    }
    results = [h_baseline]

    for name, cdir in [
        ("h/2 (630,586 cells)", SANDBOX / "case_h2"),
        ("h/4 (566,882 cells)", SANDBOX / "case_h4"),
    ]:
        r = compute_cp_ct(name, cdir)
        results.append(r)

    # Print per-level
    print(f"\n{'level':<40} {'last_t':>8} {'rows':>6} {'Cp':>10} {'Ct':>10} {'P_kW':>10}")
    print("-" * 95)
    for r in results:
        if r["missing"]:
            print(f"{r['level']:<40} MISSING (rotor_moment={r['rotor_moment_rows']} blades_force={r['blades_force_rows']})")
            continue
        print(f"{r['level']:<40} {r['last_t']:>8.0f} {r['n_rows']:>6d} {r['Cp']:>10.4f} {r['Ct']:>10.4f} {r['P_kW']:>10.3f}")

    # Richardson trend test
    valid = [r for r in results if not r["missing"]]
    if len(valid) < 3:
        print(f"\nINSUFFICIENT DATA for Richardson trend ({len(valid)}/3 levels available)")
        return

    Cp_h, Cp_h2, Cp_h4 = valid[0]["Cp"], valid[1]["Cp"], valid[2]["Cp"]
    Ct_h, Ct_h2, Ct_h4 = valid[0]["Ct"], valid[1]["Ct"], valid[2]["Ct"]

    print("\n--- Richardson trend test (Cp) ---")
    delta_Cp_coarse = Cp_h2 - Cp_h4   # change between coarsest pair
    delta_Cp_fine   = Cp_h - Cp_h2    # change between finest pair
    monotonic_Cp = (delta_Cp_coarse * delta_Cp_fine) > 0  # same sign = monotonic
    asymptotic_Cp = abs(delta_Cp_fine) < abs(delta_Cp_coarse)  # decreasing magnitude
    print(f"Cp_h4 = {Cp_h4:.6f}")
    print(f"Cp_h2 = {Cp_h2:.6f}  ΔCp(h/2 - h/4) = {delta_Cp_coarse:+.6f}")
    print(f"Cp_h  = {Cp_h:.6f}  ΔCp(h - h/2)   = {delta_Cp_fine:+.6f}")
    print(f"Monotonic trend?  (same-sign Δ): {'YES' if monotonic_Cp else 'NO'}")
    print(f"Asymptotic?       (|Δfine| < |Δcoarse|): {'YES' if asymptotic_Cp else 'NO'}")
    print(f"|ΔCp_fine| / |Cp_h|: {abs(delta_Cp_fine)/abs(Cp_h)*100:.2f}%")

    print("\n--- Richardson trend test (Ct) ---")
    delta_Ct_coarse = Ct_h2 - Ct_h4
    delta_Ct_fine   = Ct_h - Ct_h2
    monotonic_Ct = (delta_Ct_coarse * delta_Ct_fine) > 0
    asymptotic_Ct = abs(delta_Ct_fine) < abs(delta_Ct_coarse)
    print(f"Ct_h4 = {Ct_h4:.6f}")
    print(f"Ct_h2 = {Ct_h2:.6f}  ΔCt(h/2 - h/4) = {delta_Ct_coarse:+.6f}")
    print(f"Ct_h  = {Ct_h:.6f}  ΔCt(h - h/2)   = {delta_Ct_fine:+.6f}")
    print(f"Monotonic trend?  (same-sign Δ): {'YES' if monotonic_Ct else 'NO'}")
    print(f"Asymptotic?       (|Δfine| < |Δcoarse|): {'YES' if asymptotic_Ct else 'NO'}")
    print(f"|ΔCt_fine| / |Ct_h|: {abs(delta_Ct_fine)/abs(Ct_h)*100:.2f}%")

    print("\n--- Verdict ---")
    monotonic_overall = monotonic_Cp and monotonic_Ct
    print(f"Cp monotonic: {monotonic_Cp}")
    print(f"Ct monotonic: {monotonic_Ct}")
    print(f"Overall monotonic convergence trend: {'PASS' if monotonic_overall else 'FAIL'}")

    # Per scope: mesh-density vs case-spec root cause attribution
    rel_shift_Cp = abs(Cp_h - Cp_h4) / abs(Cp_h)
    print(f"\nRelative |Cp_h - Cp_h/4| / |Cp_h| = {rel_shift_Cp*100:.2f}%")
    if rel_shift_Cp > 0.10:
        print("=> Mesh density NON-trivial impact (>10%) — under-resolution joins case-spec as compound issue.")
    else:
        print("=> Mesh density LOW impact (<10%) — case-spec confirmed as primary root cause (B57 scope).")


if __name__ == "__main__":
    main()
